# Generated by Django 5.0.6 on 2024-05-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson_link'),
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('amount_payment', models.DecimalField(decimal_places=2, help_text='Введите сумму оплаты', max_digits=7, verbose_name='Сумма оплаты')),
                ('method_payment', models.CharField(choices=[('TF', 'Transfer'), ('CH', 'Cash')], default='TF', help_text='Выберите способ оплаты', max_length=2, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, help_text='Выберите название оплаченного курса', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, help_text='Выберите название оплаченного урока', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Выберите имя пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-date_payment', 'user'),
            },
        ),
    ]
