# Generated by Django 5.0.6 on 2024-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_payment',
            field=models.PositiveIntegerField(help_text='Введите сумму оплаты', verbose_name='Сумма оплаты'),
        ),
    ]
