# Generated by Django 5.0.6 on 2024-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, help_text='Добавьте ссылку на видео', max_length=150, null=True, verbose_name='Ссылка'),
        ),
    ]
